version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - ./plugins:/usr/share/nginx/html/plugins:ro
      - ./config${CONFIG_PATH_SUBDIRECTORY}/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
    - "8080:80"
    environment:
    - NGINX_PORT=80
networks:
  drawionet: