version: '3'
services:
  lighttpd:
    image: sebp/lighttpd
    volumes:
      - ./plugins:/var/www/localhost/htdocs
      # - <config-directory>:/etc/lighttpd
    ports:
      - "20203:80"
    tty: true
networks:
  drawionet: